mapFile = 'input_map_csv.csv'
backgroundImg = "input_map.png"
outputImg = "output_mtg_map.png"
outputImgBgWhite = "output_mtg_map_bg_white.png"
outputImgBgTranspalent = "output_mtg_map_bg_transpalent.png"
cellNum = 1
pixelSize = 200
mainColor = (0, 0, 0)
headerColor = (0, 0, 0)
lineColor = (255, 255, 255)
csvFlg = True
noCsvXMax = 12
noCsvYMax = 8